[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  # Specifies `esbuild` for functions bundling  
  node_bundler = "esbuild"
  directory = "functions"
  included_files = ["functions/**"]

[build.environment]
  NODE_VERSION = "18"